version: '3.8'

services:
  node-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      args:
        - NODE_ENV=development
        - DATABASE_URL=postgres://postgres:password@db_postgres:5432/fm_remake
    depends_on:
      - postgres
    env_file:
      - ./db/.env
    volumes:
      - ./src:/usr/src/app/src
      - /node_modules
    container_name: fm-api
    networks:
      - app-tier
    expose:
      - '3001'
    ports:
      - '3001:3001'
    command: npm run docker:dev

  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: db_postgres
    user: postgres
    env_file:
      - ./db/.env
    volumes:
      - ./db/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app-tier

  cache:
    build:
      context: ./cache-redis
      dockerfile: Dockerfile
    container_name: cache
    env_file:
      - ./cache-redis/.env
    environment:
      - REDIS_URL=redis://cache:6379
    ports:
      - "6379:6379"
    expose:
      - 6379
    networks:
      - app-tier
    volumes:
      - ./cache-redis/cache:/data

networks:
  app-tier:
    driver: bridge
